# -*- coding: utf-8 -*-
"""Костин ММО ДЗ1 ИУ5-22М.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1IowlHWNpiglHQjIsw1EzxTZEt1piv9

# Бинарная классификация изображений: кошки против собак

## Цель работы

Воспроизвести обучение свёрточной нейронной сети для бинарной классификации изображений (кошки / собаки) с использованием аугментации данных и регуляризации, а затем оценить влияние одного предложенного улучшения (например, batch normalization или предобученной модели).

## Шаг 1: Загрузка и подготовка данных
"""

# Требуется Colab 2025.07 (!)

# Ячейка 1: Проверка версий
import sys
import tensorflow as tf

print(f"Версия Python: {sys.version}")
print(f"Версия TensorFlow: {tf.__version__}")

# Ячейка 2: Установка дополнительных библиотек
!pip install matplotlib numpy -q

print("Все библиотеки установлены без ошибок!")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import numpy as np
import os
import zipfile
import urllib.request
from pathlib import Path

# Ячейка 1: Скачивание с Microsoft CDN
import zipfile
import os

# Рабочая ссылка от Microsoft
url = "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"

# Скачиваем
!wget --no-check-certificate "$url" -O /content/kagglecatsanddogs_5340.zip

# Распаковываем
with zipfile.ZipFile('/content/kagglecatsanddogs_5340.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

print("Датасет распакован в /content/PetImages")

import os
import tensorflow as tf
from PIL import Image

print("Начинаю глубокую очистку изображений...")
num_skipped = 0
for folder_name in ('Cat', 'Dog'):
    folder_path = os.path.join('/content/PetImages', folder_name)
    for fname in os.listdir(folder_path):
        fpath = os.path.join(folder_path, fname)
        if not fname.lower().endswith(('.jpg', '.jpeg')):
            continue
        try:
            # Проверка заголовков через TF
            if not tf.io.is_jpeg(tf.io.read_file(fpath)):
                os.remove(fpath)
                num_skipped += 1
                continue
            # Проверка возможности открытия
            img = Image.open(fpath)
            img.verify()
        except:
            if os.path.exists(fpath):
                os.remove(fpath)
            num_skipped += 1

print(f"Очистка завершена. Удалено {num_skipped} проблемных файлов.")

import tensorflow as tf

BATCH_SIZE = 32
IMG_SIZE = (150, 150)
base_dir = '/content/PetImages'

# Загрузка данных из распакованной папки
train_batches = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.2,
    subset="training",
    seed=1337,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE)

val_batches = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.2,
    subset="validation",
    seed=1337,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE)

# Нормализация (масштабирование [0, 1])
normalization_layer = tf.keras.layers.Rescaling(1./255)
train_batches = train_batches.map(lambda x, y: (normalization_layer(x), y))
val_batches = val_batches.map(lambda x, y: (normalization_layer(x), y))

print("\nПотоки данных готовы. Теперь можно запускать обучение модели!")

# We are now using tf.data.Dataset (train_batches, val_batches)
# instead of ImageDataGenerator for better performance.
print("Using train_batches and val_batches for model training.")

from tensorflow.keras.layers import BatchNormalization

# Сброс сессии TensorFlow, чтобы избежать конфликтов
tf.keras.backend.clear_session()

# Модель с BatchNormalization
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

model.summary()

from tensorflow.keras.layers import BatchNormalization

# Сброс сессии TensorFlow, чтобы избежать конфликтов
tf.keras.backend.clear_session()

# Модель с BatchNormalization
model_bn = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model_bn.compile(optimizer='adam',
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

model_bn.summary()

from tensorflow.keras.layers import BatchNormalization

# Сброс сессии TensorFlow, чтобы избежать конфликтов
tf.keras.backend.clear_session()

# Модель с BatchNormalization
model_deep_bn = Sequential([
    # Блок 1
    Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    BatchNormalization(),
    MaxPooling2D(2,2),

    # Блок 2
    Conv2D(64, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    # Блок 3
    Conv2D(128, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    # Блок 4 (новый!)
    Conv2D(256, (3,3), activation='relu'),
    BatchNormalization(),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model_deep_bn.compile(optimizer='adam',
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

model_deep_bn.summary()

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Проверка GPU
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print('GPU device not found. Running on CPU (training will be slow).')
else:
  print(f'Found GPU at: {device_name}')

# Пересоздаем базовую модель
model = model_deep_bn

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("\nЗапуск обучения базовой модели на GPU...")
# Используем больше эпох, так как на GPU это быстро
history = model.fit(
    train_batches,
    epochs=10,
    validation_data=val_batches,
    verbose=1
)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(acc, label='Train Acc')
plt.plot(val_acc, label='Val Acc')
plt.legend()
plt.title('Accuracy')

plt.subplot(1,2,2)
plt.plot(loss, label='Train Loss')
plt.plot(val_loss, label='Val Loss')
plt.legend()
plt.title('Loss')
plt.show()

# Исправлено: используем val_batches вместо val_generator
loss_v, acc_v = model.evaluate(val_batches)
print(f'Validation Accuracy: {acc_v:.4f}')

# Оценка
val_loss_bn, val_acc_bn = model_bn.evaluate(val_batches)
print(f"\nМодель с BatchNormalization - Validation Accuracy: {val_acc_bn:.4f}")